import com.google.common.collect.ImmutableList;

public class Configuration {

    private static final ImmutableList<String> SWEARS = getSwearsImmutableList();

    public static ImmutableList<String> getSwears(){
        return SWEARS;
    }

    private static ImmutableList<String> getSwearsImmutableList(){
        ImmutableList.Builder<String> listBuilder = ImmutableList.builder();
        for (String line : RAW_SWEARS.split("\\n")){
            listBuilder.add(line.toLowerCase());
        }
        return listBuilder.build();
    }

    private static final String RAW_SWEARS =
            "damn\n" +
            "horny\n" +
            "sex\n" +
            "penis\n" +
            "piss\n" +
            "2girls1cup\n" +
            "wtf\n" +
            "anal\n" +
            "arbeit macht frei\n" +
            "Arsch\n" +
            "Arschloch\n" +
            "Arse\n" +
            "Arsehole\n" +
            "arseholes\n" +
            "ass\n" +
            "asshole\n" +
            "assholes\n" +
            "auschwitz\n" +
            "ausschwitz\n" +
            "Baiser\n" +
            "Bellend\n" +
            "bitch\n" +
            "blow job\n" +
            "Blowjob\n" +
            "Bollocks\n" +
            "Bougnoul\n" +
            "Bullshit\n" +
            "buttfuck\n" +
            "buttfucker\n" +
            "cabron\n" +
            "Chink\n" +
            "Chinky\n" +
            "coño\n" +
            "Cock\n" +
            "cock sucker\n" +
            "Cocks\n" +
            "Cocksucker\n" +
            "comepollas\n" +
            "comepoyas\n" +
            "Connard\n" +
            "Cul\n" +
            "Cum\n" +
            "Cunt\n" +
            "cunts\n" +
            "Dick\n" +
            "Dickhead\n" +
            "Dicks\n" +
            "Drecksau\n" +
            "drecksjude\n" +
            "Enculé\n" +
            "encular\n" +
            "Endlösung\n" +
            "Endsieg\n" +
            "Führer\n" +
            "facha\n" +
            "fag\n" +
            "Faggot\n" +
            "falangista\n" +
            "fascista\n" +
            "Fellatio\n" +
            "Ferme ta gueule\n" +
            "fick dich\n" +
            "Fils de pute\n" +
            "fistfuck\n" +
            "follada\n" +
            "Fook\n" +
            "Fooker\n" +
            "Fooking\n" +
            "Fotze\n" +
            "Foutre\n" +
            "foyada\n" +
            "Fuck\n" +
            "Fucker\n" +
            "Fuckers\n" +
            "Fucking\n" +
            "goatse\n" +
            "Grosse merde\n" +
            "heil hitler\n" +
            "hijo puta\n" +
            "hijoputa\n" +
            "Hitler\n" +
            "Japseye\n" +
            "jilipollas\n" +
            "Jizz\n" +
            "joder\n" +
            "judenmutter\n" +
            "judensöhne\n" +
            "Kike\n" +
            "leck mich\n" +
            "mamada\n" +
            "mamado\n" +
            "mamarla\n" +
            "Mong\n" +
            "moraco\n" +
            "motherfucker\n" +
            "Motherfucking\n" +
            "Nègre\n" +
            "Nazi\n" +
            "neger\n" +
            "negrata\n" +
            "negrero\n" +
            "Nigga\n" +
            "Nigger\n" +
            "niggers\n" +
            "Niquer\n" +
            "Pédé\n" +
            "pajear\n" +
            "pajote\n" +
            "Paki\n" +
            "pakis\n" +
            "panchito\n" +
            "pedófila\n" +
            "pederasta\n" +
            "pedofila\n" +
            "polla\n" +
            "porno\n" +
            "poya\n" +
            "Prick\n" +
            "Pricks\n" +
            "prostituir\n" +
            "proxeneta\n" +
            "Pussy\n" +
            "puta\n" +
            "Putain\n" +
            "Pute\n" +
            "Queer\n" +
            "racista\n" +
            "raecarruth\n" +
            "raghead\n" +
            "ragheads\n" +
            "rallig\n" +
            "ramera\n" +
            "rammeln\n" +
            "rape\n" +
            "rassenlehre\n" +
            "rattig\n" +
            "reichskristall\n" +
            "reisfresser\n" +
            "renob\n" +
            "rentafuck\n" +
            "rentafuck\n" +
            "retrasada\n" +
            "retrasado\n" +
            "reubeu\n" +
            "ril\n" +
            "rimjob\n" +
            "rimming\n" +
            "rital\n" +
            "roach\n" +
            "robber\n" +
            "rosbif\n" +
            "rosette\n" +
            "rula\n" +
            "ruski\n" +
            "ruskoff\n" +
            "ruskov\n" +
            "s&m\n" +
            "s-c-v-m\n" +
            "s.hit\n" +
            "s1ut\n" +
            "sackgesicht\n" +
            "sado-masochistic\n" +
            "sadomaso\n" +
            "sadomasochistic\n" +
            "sadomasoquismo\n" +
            "sadomasoquista\n" +
            "salop\n" +
            "salopard\n" +
            "salope\n" +
            "samckdaddy\n" +
            "samen\n" +
            "sandm\n" +
            "sandnigger\n" +
            "sarasa\n" +
            "sarracena\n" +
            "sarraceno\n" +
            "satan\n" +
            "saubeutel\n" +
            "sauhund\n" +
            "sausagejockey\n" +
            "sc*m\n" +
            "scat\n" +
            "schamhaar\n" +
            "scheiss\n" +
            "schlampe\n" +
            "schleu\n" +
            "schleuh\n" +
            "schlitzauge\n" +
            "schlong\n" +
            "schutzstaffel\n" +
            "schwanz\n" +
            "schwuchtel\n" +
            "scrote\n" +
            "scum\n" +
            "scum!\n" +
            "shít\n" +
            "sh!t\n" +
            "sh!te\n" +
            "sh!tes\n" +
            "sh1't\n" +
            "sh1t\n" +
            "sh1te\n" +
            "sh1thead\n" +
            "sh1theads\n" +
            "shadybackroomdealings\n" +
            "shadydealings\n" +
            "shag\n" +
            "shaggers\n" +
            "shaggin\n" +
            "shagging\n" +
            "shat\n" +
            "shawtypimp\n" +
            "sheep-l0ver\n" +
            "sheep-l0vers\n" +
            "sheep-lover\n" +
            "sheep-lovers\n" +
            "sheep-shaggers\n" +
            "sheepl0ver\n" +
            "sheepl0vers\n" +
            "sheeplover\n" +
            "sheepshaggers\n" +
            "sheethead\n" +
            "sheetheads\n" +
            "sheister\n" +
            "shhit\n" +
            "shit\n" +
            "shit4brains\n" +
            "shitass\n" +
            "shitbag\n" +
            "shitbagger\n" +
            "shitbrains\n" +
            "shitbreath\n" +
            "shitcunt\n" +
            "shitdick\n" +
            "shiteater\n" +
            "shited\n" +
            "shitface\n" +
            "shitfaced\n" +
            "shitforbrains\n" +
            "shitfuck\n" +
            "shitfucker\n" +
            "shitfull\n" +
            "shithapens\n" +
            "shithappens\n" +
            "shithead\n" +
            "shithole\n" +
            "shithouse\n" +
            "shiting\n" +
            "shitings\n" +
            "shitoutofluck\n" +
            "shits\n" +
            "shitspitter\n" +
            "shitstabber\n" +
            "shitstabbers\n" +
            "shitstain\n" +
            "shitted\n" +
            "shitter\n" +
            "shitters\n" +
            "shittiest\n" +
            "shitting\n" +
            "shittings\n" +
            "shitty\n" +
            "shiz\n" +
            "shiznit\n" +
            "shortfuck\n" +
            "shortfuck\n" +
            "shyte\n" +
            "sinnfein\n" +
            "sinnfein's\n" +
            "skeet\n" +
            "skullfuck\n" +
            "slag\n" +
            "slanteye\n" +
            "slanteye\n" +
            "slut\n" +
            "slutbag\n" +
            "sluts\n" +
            "slutt\n" +
            "slutting\n" +
            "slutty\n" +
            "slutwear\n" +
            "slutwhore\n" +
            "slutwhore\n" +
            "smackdaddy\n" +
            "smackthemonkey\n" +
            "smagma\n" +
            "smartass\n" +
            "smeg\n" +
            "snortingcoke\n" +
            "sonofabitch\n" +
            "sonofbitch\n" +
            "soplapollas\n" +
            "Spacka\n" +
            "Spast\n" +
            "Spasten\n" +
            "Spasti\n" +
            "Spaz\n" +
            "Spunk\n" +
            "Spunkbubble\n" +
            "subnormal\n" +
            "sudaca\n" +
            "Te faire enculer\n" +
            "Tranny\n" +
            "Twat\n" +
            "verga\n" +
            "vergasen\n" +
            "violar\n" +
            "Violer\n" +
            "Wank\n" +
            "Wanker\n" +
            "chuj\n" +
            "chój\n" +
            "chwdp\n" +
            "cipa\n" +
            "cipo\n" +
            "cipsko\n" +
            "czarnuch\n" +
            "Fiut\n" +
            "Fiucie\n" +
            "hoj\n" +
            "hój\n" +
            "huj\n" +
            "HWDP\n" +
            "jebać\n" +
            "jebanie\n" +
            "jebca\n" +
            "kórwa\n" +
            "korwa\n" +
            "kurwa\n" +
            "kurwia\n" +
            "kurwiszon\n" +
            "kutas\n" +
            "kutafon\n" +
            "mineciarz\n" +
            "nekrofil\n" +
            "odpierdol\n" +
            "odbyt\n" +
            "odjebało\n" +
            "pedał\n" +
            "pedal\n" +
            "pederasta\n" +
            "pierdol\n" +
            "pierdolona\n" +
            "pierdolić\n" +
            "pierdolic\n" +
            "pizda\n" +
            "przejebane\n" +
            "przyjeb\n" +
            "rozpierdalać\n" +
            "rozpierdolony\n" +
            "rozpierdolone\n" +
            "ruchać\n" +
            "ruhać\n" +
            "ruchanie\n" +
            "ruhanie\n" +
            "Skurwiel\n" +
            "skórwiel\n" +
            "skorwiel\n" +
            "sranie\n" +
            "wyjebć\n" +
            "wyjebac\n" +
            "wyjebany\n" +
            "wypierdol\n" +
            "zajebać\n" +
            "zajebane\n" +
            "zajebany\n" +
            "Malaka\n" +
            "Malakas\n" +
            "Mlk\n" +
            "Vlamenos\n" +
            "Vlameno\n" +
            "Vlamene\n" +
            "Anapire\n" +
            "Arxidi\n" +
            "Mouni\n" +
            "Muni\n" +
            "Mounia\n" +
            "Mounara\n" +
            "Arxidi\n" +
            "Arxidia\n" +
            "Poutsa\n" +
            "Poutsas\n" +
            "Gamw\n" +
            "Gamo\n" +
            "Gamaw\n" +
            "Gamao\n" +
            "Gamwto\n" +
            "Gamoto\n" +
            "Gamias\n" +
            "Kolo\n" +
            "Kwlo\n" +
            "Kolos\n" +
            "Kwlos\n" +
            "Kwlara\n" +
            "Kolara\n" +
            "Poutsaras\n" +
            "Gaula\n" +
            "Gaulo\n" +
            "Kavla\n" +
            "Xynw\n" +
            "Xyno\n" +
            "Xino\n" +
            "Papari\n" +
            "Paparia\n" +
            "Pousti\n" +
            "Poustis\n" +
            "Partouza\n" +
            "Mpastardos\n" +
            "Bastardos\n" +
            "Mpastarde\n" +
            "Bastarde\n" +
            "Bastardaki\n" +
            "Gamimenos\n" +
            "Gamimene\n" +
            "Gamimeni\n" +
            "Gamimeno\n" +
            "Poutana\n" +
            "Kariola\n" +
            "Mounodoulos\n" +
            "Mounodoule\n" +
            "Psoli\n" +
            "Psoles\n" +
            "Psola\n" +
            "Zwo\n" +
            "Zwadi\n" +
            "Zwa\n" +
            "Mounopano\n" +
            "Mounopana\n" +
            "Poustraki\n" +
            "Karkino\n" +
            "Karkinos\n" +
            "Viazw\n" +
            "Viasw\n" +
            "Skato\n" +
            "Skata\n" +
            "Karioli\n" +
            "Xamoura\n" +
            "gamh8eite\n" +
            "voulgare\n" +
            "partouza";
}
